---
title: "COVID_timeline_map"
author: "Richard Cottrell"
date: "19/04/2020"
output: html_document
---

#libraries

```{r}
  
library(chron)
library(here)
library(RColorBrewer)
library(lattice)
library(ncdf4)
library(oce)
library(raster)
library(rgdal)
library(stats)
library(ggmap)
library(rworldmap)
library(tidyverse)
library(ggpubr)
library(janitor)
library(lubridate)
library(patchwork)
library(countrycode)
library(LaCroixColoR)

#install.packages(c("cowplot", "googleway", "ggplot2", "ggrepel", "ggspatial", "libwgeom", "sf", "rnaturalearth", "rnaturalearthdata"))
library("rnaturalearth")
library("rnaturalearthdata")
library("sf")
library(sp)



```



Color pallettes
```{r}
#colors
cols = rev(colorRampPalette(brewer.pal(11, 'Spectral'))(255)) # rainbow color scheme for plotting

```


Data

```{r}
#Our World in Data COVID (pulled both per million and totals)
#covid_permil<-read.csv("covid-confirmed-cases-per-million-since-1-per-million.csv") 
covid_permil <- read_csv(here("data", "covid-confirmed-cases-per-million-since-1-per-million.csv")) %>% 
  mutate(Date = mdy(Date)) %>% 
  clean_names()
  




covid_tot <- read_csv(here("data","total-cases-covid-19.csv")) %>% 
  mutate(Date = mdy(Date)) %>% 
  clean_names()

chn_news<-read_csv(here("data", "china_news.csv"))
  head(chn_news)

covid_countries <- covid_permil %>% 
  filter(iso3 %in% c("USA","CHN","IND","AUS", "CHL", "NOR",
       "PER","CAN", "ZAF", "KEN"))
  

max_pt<-log(max(covid_countries$cases_per_million+1))
dates <- na.omit(unique(chn_news$clean_date))
```


Plots


#Time series
```{r}
#PLOT WITH EXAMPLE DATES (MODIFY BASED ON NEWS SELECTION)
p0<-ggplot(covid_countries, aes(x=date, y=log(cases_per_million+1), group=entity)) +
  geom_line(aes(color=entity), size=2)+
  labs(x = "Time", y="LN(Confirmed Cases per Million")+
  scale_x_date(date_labels = "%Y %b %d")+
  geom_vline(xintercept = as.numeric(as.Date(dates[c(1,4,5,7:10)])), linetype=2,color="black")+
  theme_pubr()+
  theme(legend.title=element_blank(),
        text=element_text(size=8),
        legend.box.spacing = unit(0.2, "cm"),
        legend.background = element_rect(colour = "transparent", fill = "transparent"),
        legend.box.background = element_rect(colour="transparent", fill="transparent"), 
        legend.position = 'none', plot.margin = unit(c(1,4,1,1), "lines"))+
  scale_color_brewer(palette="PuBu")+
  annotate("text", x = as.Date(dates[c(1,4,5,7:10)]-2), y=c(max_pt), label = c("A.","B.","C.","D.","E.","F.","G."))
#DEAL WITH MARGIN ISSUES
p1 <- ggplotGrob(p0)
p1$layout$clip[p1$layout$name == "panel"] <- "off"
grid.draw(p1)



```


#Seafood supply map
```{r}

seafood_data<-read_csv(here("data", "fish-and-seafood-consumption-per-capita.csv")) %>% 
  clean_names() %>% 
  rename(seafood_supply_caput_kg_yr = fish_and_seafood_supply_per_person_kilograms_per_year,
         region = entity,
         iso_a3 = iso3) %>% 
  filter(year==2013 & (!(is.na(iso_a3))))


trade_data <- read_csv(here("data", "imports_exports.csv")) %>% 
  rename(iso_a3 = ISO3c) %>%
  mutate(imp_from_CHN_kg = case_when(is.na(imp_from_CHN_kg)~ 0,
                                     TRUE ~ imp_from_CHN_kg)) %>% 
  mutate(exp_to_CHN_kg = case_when(is.na(exp_to_CHN_kg) ~ 0,
                                   TRUE ~ exp_to_CHN_kg)) %>% 
   mutate(imp.kg = case_when(is.na(imp.kg)~ 0,
                                     TRUE ~ imp.kg)) %>% 
  mutate(exp.kg = case_when(is.na(exp.kg) ~ 0,
                                   TRUE ~ exp.kg)) %>%
  
  mutate(total_china_trade = imp_from_CHN_kg + exp_to_CHN_kg,
         total_trade = exp.kg + imp.kg) %>% 
  mutate(prop_china = total_china_trade/total_trade )
  
  



#bounding box
bbox <- readOGR(dsn=file.path(here("shapefiles", "ne_110m_graticules_all")), layer="ne_110m_wgs84_bounding_box")

bbox <- spTransform(bbox, CRS("+proj=robin"))  # reproject bounding box
bbox_df<- fortify(bbox) #, group="ISO_TER1"


#countries
countries <- readOGR(dsn = file.path(here("shapefiles", "ne_110m_admin_0_countries")), layer="ne_110m_admin_0_countries")
#countries <- countries[!countries$iso_a3 %in% c("ATA"),] #remove antartica
countries<- spTransform(countries, CRS("+proj=robin"))
countries@data$id <- rownames(countries@data)
countries@data <- left_join(countries@data, trade_data, by="iso_a3")
countries_df<-fortify(countries)
countries_df<-left_join(countries_df, countries@data, by="id")


centroids.df <- data_frame(coordinates(countries[countries$iso_a3 %in% c("USA","CHN","IND","AUS", "CHL", "NOR", "PER","ZAF", "KEN", "MMR"),]) ) %>% mutate(label = c("A", "A", ("C  D"), "F", "E", "C" , "B", "C", "E", "A" ))


centroids.df
# countries_df<- countries_df %>% 
#   select(-c( brk_group, formal_fr, note_adm0, note_brk, name_alt, fips_10))

(p2 <- ggplot(data=bbox_df, aes(long,lat, group=group)) + geom_polygon(fill="aliceblue")+
  geom_polygon(data=countries_df, aes(x=long, y=lat, group=group,  fill=(total_china_trade)))+
  theme_nothing()+
  theme(legend.position = "bottom",
        legend.text = element_text(size=8),
        legend.title = element_text(size=8),
        legend.box.spacing = unit(-1, "cm"))+
  #scale_fill_viridis_c(direction=-1, option="C", na.value = "grey90",labels=c(2.5, 5, 7.5, 10), breaks=c(2.5e+08, 5e+08, 7.5e+08, 10e+08))+
  scale_fill_gradient2(low = "lightblue", mid = "royalblue", high = "firebrick", midpoint = 6e+8, na.value = "grey90", breaks=c(2.5e+8, 5e+8, 7.5e+8, 1e+9), labels=c(0.25, 0.5, 0.75, 1))+
  guides(fill=guide_colorbar(title.position = "top", title.hjust = 0.5, barwidth = 10, barheight = 0.5, units="cm"))+
  labs(fill=bquote(Total~seafood~trade~with~China~(MMT))) +
  ggsave(here("plots", paste0("seafood_trade_map_", Sys.Date(), ".jpg")), device="jpg", dpi=300, width=12, height=7, units="cm"))




p1



p2 <- ggplot(data=bbox_df, aes(long,lat, group=group)) + geom_polygon(fill="aliceblue")+
  geom_polygon(data=countries_df, aes(x=long, y=lat, group=group, map_id=id, fill=(prop_china)))+
  theme_nothing()+
  theme(legend.position = "bottom",
        legend.text = element_text(size=8),
        legend.title = element_text(size=8),
        legend.box.spacing = unit(-1, "cm"))+
  scale_fill_viridis_c(direction=-1, option="A", na.value = "grey90" ,labels=c(0.25,0.5,0.75), breaks=c(0.25,0.5,0.75))+
  guides(fill=guide_colorbar(title.position = "top", title.hjust = 0.5, barwidth = 10, barheight = 0.5, units="cm"))+
  labs(fill=bquote(Prop.~total~seafood~trade~from~China)) +
  ggsave(here("plots", paste0("prop_trade_map_", Sys.Date(), ".tiff")), device="tiff", dpi=300, width=12, height=7, units="cm")



```


#combine plots

```{r}

p1 <- p1+coord_cartesian(clip = "off")

ggarrange(p1, p2+coord_cartesian(clip = "off"), 
          labels="auto",
          heights = c(0.6,0.5),
          nrow = 2, ncol=1,
          align = "h") +
  ggsave(here("plots", paste0("composite_timeline_figure", Sys.Date(), ".jpg")), device="jpg", dpi=300, width = 12, height=14, units = "cm")

```

